<table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td bgcolor="#FF6600"><img src="images/portada_01.jpg" alt="Fusion Fashion - Naranja El&eacute;ctrico" width="550" height="165" border="0"></td>
        </tr>
        <tr> 
          <td height="1" bgcolor="#000000"><img src="../images/pixnegro.gif" width="1" height="1" border="0"></td>
        </tr>
        <tr> 
          <td height="1" bgcolor="#FFFFFF"> <table width="100%" height="14" border="0" cellpadding="0" cellspacing="1">
              <tr align="center" bgcolor="#CC0000" class="contenido2"> 
                <td width="16%" bgcolor="#999966"><strong><font color="#FFFFFF" size="1">OTROS 
                  COLORES</font></strong></td>
                <td width="16%"><font color="#FFFFFF" size="1">ROJO</font></td>
                <td width="16%" bgcolor="#CC0000"><font color="#FFFFFF" size="1"><a href="naranja.php">NARANJA</a></font></td>
                <td width="16%"><font color="#FFFFFF" size="1">AZUL</font></td>
                <td width="16%"><font color="#FFFFFF" size="1">VERDE</font></td>
                <td width="16%"><font color="#FFFFFF" size="1">NEGRO</font></td>
              </tr>
            </table></td>
        </tr>
      </table>