<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#FFFFFF"> 
    <td height="1"><img src="../images/pixblanco.gif" width="1" height="1"></td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="3" cellpadding="0" bgcolor="#000000">
  <tr> 
    <td width="1%"><table width="110" height="45" border="0" cellpadding="0" cellspacing="1" bgcolor="#666666">
        <tr> 
          <td align="center" bgcolor="#333333"><a href="../main/index.php"><img src="../images/logo01.gif" width="90" height="40" alt="Proyecto Fusion" border="0"></a></td>
        </tr>
      </table></td>
    <td width="99%"><table width="100%" height="45" border="0" cellpadding="5" cellspacing="1" bgcolor="#666666">
        <tr> 
          <td valign="top" bgcolor="#000000" class="contenido2"><font color="#FFFFFF"> 
            <a href="../antros/index.php">Antros</a> | <a href="../social/index.php">Social</a> 
            | <a href="../auditivo/index.php">Auditivo</a> | <a href="../fashion/index.php">Fashion</a> 
            | <a href="../urbana/index.php">Urbana</a>| <a href="../sesentagrados/index.php">60&deg;</a> 
            | <a href="../ficcion/index.php">Ficción</a><br>
            <a href="../main/contacto.php">Contáctanos</a> | <a href="../main/quees.php">Qué 
            es</a> | <a href="../main/quien.php">Quién hace</a> 
            | <a href="../main/mapa.php">Mapa</a> | <a href="../main/ayuda.php">Ayuda</a></font></td>
        </tr>
      </table></td>
  </tr>
</table>