<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#000000"> 
    <td> <div align="center"> 
        <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="740" height="50">
          <param name="movie" value="../images/headder.swf">
          <param name="quality" value="high">
          <embed src="../images/headder.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="740" height="50"></embed></object>
        </embed> </object> </div></td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td height="1"><img src="../images/pixblanco.gif" width="1" height="1"></td>
  </tr>
</table>